# This is a basic workflow to help you get started with Actions
# This file was contributed by Carlos Parada and Yamel Senih from ERP Consultores y Asociados, C.A

name: Publish With gradle to maven central

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  release:
    types: 
      - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build dist application backend
  build-app:
    name: Publish with gradle to maven central
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: 11

      - name: Publish with Gradle
        run: gradle publish
        env:
          ADEMPIERE_LIBRARY_VERSION: ${{ github.event.release.tag_name }}
          ADEMPIERE_LIBRARY_GROUP: ${{ secrets.ADEMPIERE_LIBRARY_GROUP }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
